# Generated by Django 6.0 on 2026-03-16 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0055_add_hn_feature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookmarkvote',
            name='unique_bookmark_vote',
        ),
        migrations.AddField(
            model_name='bookmarkvote',
            name='session_key',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='bookmarkvote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='bookmarkvote',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'bookmark'), name='unique_bookmark_vote'),
        ),
        migrations.AddConstraint(
            model_name='bookmarkvote',
            constraint=models.UniqueConstraint(condition=models.Q(('session_key__gt', '')), fields=('session_key', 'bookmark'), name='unique_bookmark_vote_session'),
        ),
    ]
